---
name: ğŸ·ï¸ Github Release
run-name: ğŸ·ï¸ Github Release - Tag & Publish Latest Release from ${{ github.ref_name }} by @${{ github.actor }}
on:
  workflow_dispatch:

env:
  CI: ${{ vars.CI }}
  HUSKY: ${{ vars.HUSKY }}

jobs:
  github-release:
    name: ğŸ·ï¸ Github Release
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ”‘ Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: ğŸ›’ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: ğŸ”§ Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - uses: ./.github/actions/setup

      - name: ğŸ”– Github Release (Tag + Release)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm nx:release
